In [43]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import utils
from scipy.io import loadmat
from PIL import Image
import scipy.optimize as opt

In [4]:
data = loadmat('ex3data1.mat')
X, y = data['X'], data['y'].ravel()
X = np.concatenate([np.ones((y.size , 1)) ,X], axis =1)
y[y==10] = 0
m = y.size
df =  pd.DataFrame(X)
dfX =  pd.DataFrame(X)
df['y'] = y
y = y.reshape(y.shape[0],1)
y.shape
df.tail()

0    1    2    3    4    5    6    7    8    9  ...  392  393  394  \
4995  1.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  ...  0.0  0.0  0.0   
4996  1.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  ...  0.0  0.0  0.0   
4997  1.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  ...  0.0  0.0  0.0   
4998  1.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  ...  0.0  0.0  0.0   
4999  1.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  ...  0.0  0.0  0.0   

      395  396  397  398  399  400  y  
4995  0.0  0.0  0.0  0.0  0.0  0.0  9  
4996  0.0  0.0  0.0  0.0  0.0  0.0  9  
4997  0.0  0.0  0.0  0.0  0.0  0.0  9  
4998  0.0  0.0  0.0  0.0  0.0  0.0  9  
4999  0.0  0.0  0.0  0.0  0.0  0.0  9  

[5 rows x 402 columns]

In [5]:
y

array([[0],
       [0],
       [0],
       ...,
       [9],
       [9],
       [9]], dtype=uint8)

In [6]:
#Randomly Selecting 100 values
rand_val = np.random.choice(m , 100, replace = False)
sel  = X[rand_val,:]

#utils.displayData(sel)

In [7]:
#show random 100 images

In [8]:
def sigmoid(z):                #sigmoid function
    return 1/(1+np.exp(-z))

In [9]:
def h(theta, X):             #hypothesis function
    return sigmoid(np.dot(X, theta))

In [45]:
def cost_func(theta, X, y):
    h1 = h(theta, X)
    J = float(-(np.dot(y.T, np.log(h1)) + np.dot((1-y).T, np.log(1 - h1)))/m) + lambd*((theta*theta).sum() - (theta[0]*theta[0]))/(2*m)
    return J[0]

def grad(theta , X ,y ):
    h1 = h(theta, X)
    grad = np.dot(X.T , (h1 - y))/m + lambd*theta/m
    grad[0] = np.dot(X.T , (h1 - y))[0]/m
    return grad

In [46]:
lambd = 0.1
initial_theta  = np.zeros((X.shape[1], 1))
alpha = 0.001
theta = initial_theta

def optim(X,y,theta):
    for i in range(100000):
        theta -= alpha*grad(X,y,theta)
        if(i%10000 ==0):
            print("Iteration " + str(i) + "  Cost: " + str(cost_func(X,y,theta)) )
    return h(theta, X)    


In [47]:
def y_k(temp_y, i):
    index = temp_y==i
    #print(index)
    temp_y[:] =0
    temp_y[index] = 1
    return temp_y

In [48]:
#optim(X,y,theta).shape
hypo =[]
for i in range(10):
    print("------ " +str(i)+ "-------" )
    temp_y = np.copy(y)
    temp_y = y_k(temp_y,i)
    temp = opt.fmin_tnc(func = cost_func, 
                        x0 = theta,fprime = grad, 
                        args = (X, temp_y))
    hypo.append(temp[0])

------ 0-------


IndexError: invalid index to scalar variable.

In [14]:
hypothesis = np.zeros((m, 10))
for i in range(10):
    print("------ " +str(i)+ "-------" )
    temp_y = np.copy(y)
    temp_y = y_k(temp_y,i)
    hypothesis[:, i:i+1] = optim(X,temp_y, theta)
    temp_y

------ 0-------
Iteration 0  Cost: 0.6902694470563941
Iteration 10000  Cost: 0.10119620880648776
Iteration 20000  Cost: 0.07624681912358644
Iteration 30000  Cost: 0.06532510960377823
Iteration 40000  Cost: 0.0587559980781029
Iteration 50000  Cost: 0.0542242698632872
Iteration 60000  Cost: 0.050842187001718844
Iteration 70000  Cost: 0.04818357764199948
Iteration 80000  Cost: 0.046014808143108106
Iteration 90000  Cost: 0.044195905147595464
------ 1-------
Iteration 0  Cost: 1.0259827485033362
Iteration 10000  Cost: 0.13630598033699054
Iteration 20000  Cost: 0.08538660883291968
Iteration 30000  Cost: 0.06992144155371631
Iteration 40000  Cost: 0.06185548900401391
Iteration 50000  Cost: 0.05670229750207723
Iteration 60000  Cost: 0.05304961352363242
Iteration 70000  Cost: 0.05029313755784221
Iteration 80000  Cost: 0.0481228899854769
Iteration 90000  Cost: 0.046360295854249584
------ 2-------
Iteration 0  Cost: 0.966067072153805
Iteration 10000  Cost: 0.21076732553694044
Iteration 20000  Cost

In [15]:
 temp_y = y_k(y,1)
temp_y

array([[0],
       [0],
       [0],
       ...,
       [0],
       [0],
       [0]], dtype=uint8)

In [16]:
hypothesis

array([[9.90877519e-01, 2.02673925e-04, 1.18035715e-03, ...,
        9.85192391e-04, 1.08040387e-03, 8.96083571e-04],
       [9.76576368e-01, 4.51027201e-04, 2.64915324e-04, ...,
        1.45496156e-03, 1.71253831e-04, 6.59720019e-05],
       [3.93312021e-01, 5.40226318e-05, 1.16556417e-03, ...,
        1.14307526e-03, 1.15305146e-01, 4.43847505e-03],
       ...,
       [6.81320720e-04, 7.71230646e-03, 1.22539185e-02, ...,
        1.97061712e-03, 2.21189019e-02, 2.44478736e-01],
       [4.76362218e-04, 3.67971360e-05, 5.68995960e-06, ...,
        3.52481290e-02, 1.51155715e-02, 6.69107435e-01],
       [7.83900217e-02, 3.45711192e-05, 1.03152151e-02, ...,
        1.01662419e-01, 5.48649287e-02, 2.73558875e-02]])

In [17]:
cost_func(X,y,theta)

0.6689721744656008

In [18]:
hdf = pd.DataFrame(hypothesis)

In [19]:
hdf.tail()

0         1         2         3         4         5         6  \
4995  0.003358  0.000582  0.005097  0.023062  0.184651  0.012471  0.005360   
4996  0.003208  0.000019  0.006354  0.000013  0.003371  0.000027  0.000108   
4997  0.000681  0.007712  0.012254  0.086367  0.116427  0.111652  0.027473   
4998  0.000476  0.000037  0.000006  0.000018  0.102685  0.009395  0.000093   
4999  0.078390  0.000035  0.010315  0.000045  0.006964  0.000133  0.002179   

             7         8         9  
4995  0.008904  0.024373  0.798326  
4996  0.028408  0.227362  0.672979  
4997  0.001971  0.022119  0.244479  
4998  0.035248  0.015116  0.669107  
4999  0.101662  0.054865  0.027356

In [20]:
y

array([[0],
       [0],
       [0],
       ...,
       [0],
       [0],
       [0]], dtype=uint8)

In [36]:
a = hdf.idxmax(axis=1)
a = a.to_numpy().reshape(m,1)
a.tolist()

[[0],
 [0],
 [0],
 [0],
 [0],
 [0],
 [0],
 [0],
 [0],
 [0],
 [0],
 [0],
 [0],
 [0],
 [0],
 [0],
 [0],
 [0],
 [0],
 [0],
 [0],
 [0],
 [0],
 [0],
 [0],
 [0],
 [6],
 [0],
 [0],
 [0],
 [0],
 [0],
 [0],
 [0],
 [0],
 [0],
 [0],
 [0],
 [0],
 [0],
 [0],
 [0],
 [0],
 [0],
 [0],
 [0],
 [0],
 [0],
 [0],
 [0],
 [0],
 [0],
 [0],
 [0],
 [0],
 [0],
 [0],
 [0],
 [0],
 [0],
 [0],
 [0],
 [0],
 [0],
 [0],
 [0],
 [0],
 [0],
 [0],
 [0],
 [0],
 [0],
 [0],
 [0],
 [0],
 [0],
 [0],
 [0],
 [0],
 [0],
 [0],
 [0],
 [0],
 [0],
 [0],
 [0],
 [0],
 [0],
 [0],
 [2],
 [0],
 [0],
 [0],
 [0],
 [0],
 [0],
 [0],
 [0],
 [0],
 [0],
 [0],
 [0],
 [0],
 [0],
 [0],
 [0],
 [0],
 [0],
 [0],
 [0],
 [0],
 [0],
 [3],
 [0],
 [0],
 [0],
 [0],
 [0],
 [0],
 [0],
 [0],
 [0],
 [0],
 [0],
 [6],
 [0],
 [0],
 [0],
 [0],
 [0],
 [0],
 [0],
 [0],
 [4],
 [0],
 [0],
 [0],
 [0],
 [0],
 [0],
 [0],
 [0],
 [8],
 [0],
 [0],
 [0],
 [0],
 [0],
 [0],
 [0],
 [8],
 [0],
 [0],
 [0],
 [0],
 [0],
 [0],
 [0],
 [0],
 [0],
 [0],
 [0],
 [0],
 [0],
 [0],
 [0],
 [0]

In [37]:
def accuracy(hypothesis, y):
    return y[y==hypothesis].size/m



In [38]:
accuracy(a,y)

0.2008