In [2]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import utils
from scipy.io import loadmat
from PIL import Image
from scipy import optimize
from scipy.optimize import fmin_bfgs

In [124]:
data = loadmat('ex3data1.mat')
X, y = data['X'], data['y'].ravel()
X = np.concatenate([np.ones((y.size , 1)) ,X], axis =1)
m = y.size
df =  pd.DataFrame(X)
dfX =  pd.DataFrame(X)
df['y'] = y
#y = y.reshape(y.shape[0],1)
#y.shape
df.iloc[4990:,200:215]


200  201       202       203       204       205       206  \
4990  0.000000  0.0 -0.014407  0.083334  0.846539  0.981079  0.468345   
4991 -0.038619  0.0  0.000000  0.000000 -0.026019  0.410966  0.951095   
4992 -0.043764  0.0  0.000000  0.000000 -0.037889  0.639510  0.854440   
4993 -0.025520  0.0  0.000000  0.000000 -0.034292  0.556631  0.996501   
4994  0.001053  0.0  0.000000  0.000000 -0.025498  0.388868  1.045169   
4995  0.000000  0.0  0.000000  0.000000 -0.036797  0.647633  0.453300   
4996 -0.042064  0.0  0.000000  0.000000 -0.043854  0.725587  1.062155   
4997  0.000000  0.0  0.000000  0.000000 -0.004036  0.022999  0.574133   
4998 -0.000243  0.0  0.000000  0.000000 -0.002475 -0.007049  0.549986   
4999 -0.044351  0.0  0.000000  0.000000 -0.031026  0.507026  0.907500   

           207       208           209       210       211       212  \
4990  0.445748  0.436091  6.825225e-01  1.010343  0.468243 -0.029694   
4991  0.263750 -0.039285 -2.965562e-02  0.059989  0.683275  1.033038   
4992  0.107049 -0.026480 -2.547023e-02  0.199604  0.810096  1.025802   
4993  0.399395 -0.028254 -1.811336e-02  0.116110  0.688744  1.027338   
4994  0.589549 -0.037717 -1.250049e-02 -0.019106  0.335779  0.975641   
4995 -0.025348 -0.021461 -4.270699e-02  0.402884  0.820498  0.106469   
4996  0.391034 -0.050441 -9.090295e-03  0.044559  0.686090  1.002653   
4997  0.888907  0.881704  7.622939e-01  0.840374  0.966300  0.289337   
4998  1.046026  0.554603 -5.944904e-02  0.613744  1.018118  0.989580   
4999  0.215307 -0.027198  5.755654e-19  0.000820 -0.029658  0.224610   

           213       214  
4990  0.000082 -0.005510  
4991  0.873496  0.855035  
4992  0.584138  0.682844  
4993  0.892911  0.746805  
4994  1.023033  0.936570  
4995 -0.019882 -0.012339  
4996  0.915504  0.270314  
4997 -0.063227 -0.026421  
4998  0.991597  1.031827  
4999  0.963670  0.738628

In [125]:
input_layer_size  = 400  # 20x20 Input Images of Digits
hidden_layer_size = 25   # 25 hidden units
num_labels = 10        # 10 labels, from 1 to 10   

In [126]:
theta1 , theta2 = loadmat('ex3weights.mat')['Theta1'] , loadmat('ex3weights.mat')['Theta2']

In [127]:
    def sigmoid(z):                #sigmoid function
        return 1/(1+np.exp(-z))

In [128]:
def h(theta, X):             #hypothesis function
    return sigmoid(np.dot(X, theta))
X

array([[1., 0., 0., ..., 0., 0., 0.],
       [1., 0., 0., ..., 0., 0., 0.],
       [1., 0., 0., ..., 0., 0., 0.],
       ...,
       [1., 0., 0., ..., 0., 0., 0.],
       [1., 0., 0., ..., 0., 0., 0.],
       [1., 0., 0., ..., 0., 0., 0.]])

In [129]:
    hypothesis = np.ones((m,10))
    z1 = h(theta1.T, X)
    a1 = np.concatenate([np.ones((m,1)), z1] , axis = 1)
    a2 = h(theta2.T , a1)

In [130]:
a2.shape

(5000, 10)

In [131]:
theta1.shape

(25, 401)

In [132]:
X

array([[1., 0., 0., ..., 0., 0., 0.],
       [1., 0., 0., ..., 0., 0., 0.],
       [1., 0., 0., ..., 0., 0., 0.],
       ...,
       [1., 0., 0., ..., 0., 0., 0.],
       [1., 0., 0., ..., 0., 0., 0.],
       [1., 0., 0., ..., 0., 0., 0.]])

In [137]:
p=np.argmax(a2, axis =1) +1
p

array([10, 10, 10, ...,  9,  9,  9])

In [135]:
def accuracy(hypothesis, y):
    return y[y==hypothesis].size/m

In [136]:
accuracy(p, y)

0.9752

In [5]:
np.random.rand(3,4)*2*0.12-0.12

array([[-0.10413329, -0.08855674, -0.11718842, -0.0379407 ],
       [ 0.10731391,  0.09964343, -0.10785796, -0.04655335],
       [ 0.02476425, -0.07492432,  0.11754677,  0.026633  ]])